name: Flutter CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Flutter pub get
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Run unit and widget tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release
